<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<dict>
  <key>fileTypes</key>
  <array> 
    <string>qua</string>
   </array>
  <key>name</key>
  <string>Qua</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Qua</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(if | while | forever | loop)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bdefine\b | \bassign\b | \bpublic\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bvalue\b | \bset\b | \bequals\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bmain\b | \bend\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bmain\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bend\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\bfunction\b | \bstatic\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\blog\b | \bprint\b)</string>
          <key>name</key>
          <string>text.Qua</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Qua</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.Qua</string>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Qua</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Qua</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>constant.character.escape.Qua</string>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.Qua</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
  </dict>
</dict>
</plist>
